learning_templates/basic_app/urls.py
from django.urls import path, include
from basic_app import views


#TEMPLATE TAGGING
app_name = 'basic_app' #This is the appname it is looking for in the html page
urlpatterns = [
    path('other', views.other, name= 'other'), #name=other is what the template tagging is looking for in the html page.
    path('relative_url_templates', views.relative_url_templates, name= 'relative_url_templates'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),

]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request,'basic_app/index.html')


def other(request):
    return render(request, 'basic_app/other.html')

def relative_url_templates(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HELLO</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">>
      <div class="container">
        <ul class="navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class="nav-link" href="{% url 'basic_app:other' %}">OTHER</a></li>
          <li><a class="nav-link" href="{% url 'basic_app:relative_url_templates' %}">Relative</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      <!-- ANYTHING OUTSIDE OF THIS WILL BE INHERITED IF YOU EXTEND -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    <h1>WELCOME TO INDEX</h1>
  </body>
</html>

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance</h2>

    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <!-- The basci_app is looking for the app name in basic_app.urls file and is find the 'other url in the name' -->
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">INDEX</a>
  </body>
</html>